version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "revred"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      testing-packages:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "Moq"
          - "FluentAssertions"
          - "coverlet*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "revred"
    commit-message:
      prefix: "ci"
      include: "scope"